import jsPDF from "jspdf";
import { BrandData } from "./types";
import { MockData } from "./mockData";

// ── helpers ───────────────────────────────────────────────────────────────────
const W = 595.28;
const M = 48;
const CW = W - M * 2;

function rgb(hex: string): [number, number, number] {
  const n = parseInt(hex.replace("#", ""), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}
function tc(pdf: jsPDF, hex: string) { pdf.setTextColor(...rgb(hex)); }
function fc(pdf: jsPDF, hex: string) { pdf.setFillColor(...rgb(hex)); }
function dc(pdf: jsPDF, hex: string) { pdf.setDrawColor(...rgb(hex)); }

function label(pdf: jsPDF, text: string, x: number, y: number) {
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(8);
  tc(pdf, "#94a3b8");
  pdf.text(text.toUpperCase(), x, y);
}

function bodyText(pdf: jsPDF, text: string, x: number, y: number, maxWidth = CW, color = "#475569"): number {
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(10);
  tc(pdf, color);
  const lines = pdf.splitTextToSize(text, maxWidth);
  pdf.text(lines, x, y);
  return lines.length * 14;
}

function card(pdf: jsPDF, x: number, y: number, w: number, h: number, bg = "#f8fafc", border = "#e2e8f0") {
  fc(pdf, bg); dc(pdf, border); pdf.setLineWidth(0.5);
  pdf.roundedRect(x, y, w, h, 4, 4, "FD");
}

function accentBar(pdf: jsPDF) {
  fc(pdf, "#2563eb"); pdf.rect(0, 0, W / 2, 4, "F");
  fc(pdf, "#6366f1"); pdf.rect(W / 2, 0, W / 2, 4, "F");
}

function pageHeader(pdf: jsPDF, agent: string, title: string) {
  accentBar(pdf);
  label(pdf, agent, M, 24);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(20);
  tc(pdf, "#0f172a");
  pdf.text(title, M, 48);
}

function footer(pdf: jsPDF) {
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(8);
  tc(pdf, "#94a3b8");
  dc(pdf, "#e2e8f0"); pdf.setLineWidth(0.5);
  pdf.line(M, 820, W - M, 820);
  pdf.text("Generated by BrandForge AI", M, 832);
  pdf.text("Confidential — Brand Kit", W - M, 832, { align: "right" });
}

// ── PAGE 1: COVER ─────────────────────────────────────────────────────────────
function coverPage(pdf: jsPDF, data: BrandData, mock: MockData) {
  fc(pdf, "#0f172a"); pdf.rect(0, 0, W, 841.89, "F");
  fc(pdf, "#1e3a8a"); pdf.ellipse(W - 80, 80, 180, 180, "F");
  fc(pdf, "#312e81"); pdf.ellipse(60, 780, 130, 130, "F");

  // Logo
  fc(pdf, "#2563eb"); pdf.roundedRect(M, 52, 24, 24, 3, 3, "F");
  pdf.setFont("helvetica", "bold"); pdf.setFontSize(13);
  tc(pdf, "#ffffff"); pdf.text("B", M + 8, 68);
  pdf.setFontSize(11); tc(pdf, "#94a3b8");
  pdf.text("BRANDFORGE", M + 30, 68);

  // Badge
  pdf.setFontSize(9); pdf.setFont("helvetica", "bold"); tc(pdf, "#3b82f6");
  pdf.text("AI BRAND IDENTITY REPORT", M, 130);

  // Startup name
  pdf.setFont("helvetica", "bold"); pdf.setFontSize(42); tc(pdf, "#ffffff");
  const nameLines = pdf.splitTextToSize(data.startupName, CW);
  pdf.text(nameLines, M, 165);

  // Tagline
  const nameH = nameLines.length * 48;
  pdf.setFont("helvetica", "bolditalic"); pdf.setFontSize(16); tc(pdf, "#93c5fd");
  pdf.text(`"${mock.copy.tagline}"`, M, 165 + nameH + 10);

  // Elevator pitch
  const pitchY = 165 + nameH + 30;
  pdf.setFont("helvetica", "normal"); pdf.setFontSize(10); tc(pdf, "#64748b");
  const pitchLines = pdf.splitTextToSize(mock.copy.elevatorPitch, CW - 40);
  pdf.text(pitchLines, M, pitchY);

  // Bottom row
  pdf.setFont("helvetica", "normal"); pdf.setFontSize(9); tc(pdf, "#475569");
  pdf.text("Industry", M, 780);
  pdf.setFont("helvetica", "bold"); tc(pdf, "#94a3b8");
  pdf.text(data.industry, M, 793);

  pdf.setFont("helvetica", "normal"); tc(pdf, "#475569");
  pdf.text("Coherence Score", W - M, 780, { align: "right" });
  pdf.setFont("helvetica", "bold"); pdf.setFontSize(28); tc(pdf, "#3b82f6");
  pdf.text(`${mock.coherence.score}%`, W - M, 810, { align: "right" });
}

// ── PAGE 2: RESEARCH ──────────────────────────────────────────────────────────
function researchPage(pdf: jsPDF, mock: MockData) {
  pageHeader(pdf, "Research Agent · Market Intelligence", "Market Research & Audience Analysis");
  let y = 68;

  // Audience
  label(pdf, "Target Audience", M, y); y += 10;
  card(pdf, M, y, CW, 52, "#eff6ff", "#bfdbfe");
  dc(pdf, "#2563eb"); pdf.setLineWidth(2); pdf.line(M, y, M, y + 52);
  bodyText(pdf, mock.research.audience, M + 12, y + 14, CW - 20, "#1e40af");
  y += 62;

  // Pain points
  label(pdf, "Audience Pain Points", M, y); y += 10;
  const ppH = Math.min(mock.research.audiencePainPoints.length * 18 + 20, 90);
  card(pdf, M, y, CW, ppH);
  let py = y + 14;
  mock.research.audiencePainPoints.forEach((p) => {
    pdf.setFont("helvetica", "bold"); pdf.setFontSize(10); tc(pdf, "#2563eb");
    pdf.text("›", M + 8, py);
    bodyText(pdf, p, M + 18, py, CW - 30);
    py += 16;
  });
  y += ppH + 10;

  // Competitors
  label(pdf, "Competitor Analysis", M, y); y += 10;
  mock.research.competitors.forEach((c) => {
    const ch = 72;
    card(pdf, M, y, CW, ch);
    pdf.setFont("helvetica", "bold"); pdf.setFontSize(11); tc(pdf, "#0f172a");
    pdf.text(c.name, M + 12, y + 16);
    const half = (CW - 24) / 2;
    label(pdf, "Strengths", M + 12, y + 30);
    pdf.setFillColor(220, 252, 231); pdf.roundedRect(M + 10, y + 32, 8, 8, 2, 2, "F");
    bodyText(pdf, c.strengths, M + 12, y + 44, half - 4, "#16a34a");
    label(pdf, "Weaknesses", M + 14 + half, y + 30);
    bodyText(pdf, c.weaknesses, M + 14 + half, y + 44, half - 4, "#dc2626");
    y += ch + 8;
  });

  // Trends
  label(pdf, "Industry Trends", M, y); y += 12;
  let tx = M;
  mock.research.marketTrends.forEach((t) => {
    const tw = pdf.getStringUnitWidth(t) * 10 + 16;
    fc(pdf, "#eff6ff"); dc(pdf, "#bfdbfe"); pdf.roundedRect(tx, y, tw, 16, 8, 8, "FD");
    pdf.setFont("helvetica", "bold"); pdf.setFontSize(8); tc(pdf, "#1d4ed8");
    pdf.text(t, tx + 8, y + 11);
    tx += tw + 6;
  });
  y += 26;

  label(pdf, "Market Positioning Insight", M, y); y += 10;
  card(pdf, M, y, CW, 44, "#eff6ff", "#bfdbfe");
  bodyText(pdf, mock.research.marketPositioning, M + 12, y + 16, CW - 24, "#1e40af");

  footer(pdf);
}

// ── PAGE 3: STRATEGY ──────────────────────────────────────────────────────────
function strategyPage(pdf: jsPDF, mock: MockData) {
  pageHeader(pdf, "Strategy Agent · Brand Foundation", "Mission, Vision & Brand Strategy");
  let y = 68;

  // Mission + Vision side by side
  const hw = (CW - 8) / 2;
  [
    { label: "Mission", text: mock.strategy.mission, bg: "#f5f3ff", border: "#e9d5ff", tc: "#7c3aed", body: "#1e1b4b" },
    { label: "Vision", text: mock.strategy.vision, bg: "#eef2ff", border: "#c7d2fe", tc: "#4338ca", body: "#1e1b4b" },
  ].forEach(({ label: lbl, text, bg, border, tc: tcolor, body }, i) => {
    const cx = M + i * (hw + 8);
    const lines = pdf.splitTextToSize(text, hw - 20);
    const h = lines.length * 14 + 36;
    card(pdf, cx, y, hw, h, bg, border);
    pdf.setFont("helvetica", "bold"); pdf.setFontSize(8); tc(pdf, tcolor);
    pdf.text(lbl.toUpperCase(), cx + 10, y + 16);
    bodyText(pdf, text, cx + 10, y + 28, hw - 20, body);
  });

  const mlines = pdf.splitTextToSize(mock.strategy.mission, hw - 20);
  const vlines = pdf.splitTextToSize(mock.strategy.vision, hw - 20);
  y += Math.max(mlines.length, vlines.length) * 14 + 46;

  // Positioning
  card(pdf, M, y, CW, 58, "#f8fafc", "#6366f1");
  dc(pdf, "#6366f1"); pdf.setLineWidth(3); pdf.line(M, y, M, y + 58);
  label(pdf, "Positioning Statement", M + 10, y + 14);
  pdf.setFont("helvetica", "bold"); pdf.setFontSize(11); tc(pdf, "#1e293b");
  const posLines = pdf.splitTextToSize(mock.strategy.positioningStatement, CW - 20);
  pdf.text(posLines, M + 10, y + 28);
  y += 68;

  // Personality pills
  label(pdf, "Brand Personality", M, y); y += 12;
  let px = M;
  mock.strategy.brandPersonality.forEach((p) => {
    const pw = pdf.getStringUnitWidth(p) * 10 + 16;
    fc(pdf, "#eff6ff"); dc(pdf, "#bfdbfe"); pdf.roundedRect(px, y, pw, 16, 8, 8, "FD");
    pdf.setFont("helvetica", "bold"); pdf.setFontSize(9); tc(pdf, "#1d4ed8");
    pdf.text(p, px + 8, y + 11);
    px += pw + 6;
  });
  y += 26;

  // Voice
  label(pdf, "Brand Voice", M, y); y += 10;
  const vlines2 = pdf.splitTextToSize(mock.strategy.brandVoice, CW - 20);
  card(pdf, M, y, CW, vlines2.length * 14 + 24);
  bodyText(pdf, mock.strategy.brandVoice, M + 10, y + 16, CW - 20);
  y += vlines2.length * 14 + 34;

  // Messaging strategy
  label(pdf, "Messaging Strategy", M, y); y += 10;
  const mslines = pdf.splitTextToSize(mock.strategy.messagingStrategy, CW - 20);
  card(pdf, M, y, CW, mslines.length * 14 + 24);
  bodyText(pdf, mock.strategy.messagingStrategy, M + 10, y + 16, CW - 20);

  footer(pdf);
}

// ── PAGE 4: DESIGN ────────────────────────────────────────────────────────────
function designPage(pdf: jsPDF, mock: MockData) {
  pageHeader(pdf, "Design Agent · Visual Identity", "Color Palette, Typography & Visual System");
  let y = 68;

  // Primary palette
  label(pdf, "Primary Color Palette", M, y); y += 12;
  mock.design.primaryPalette.forEach((c, i) => {
    const x = M + i * 90;
    fc(pdf, c.hex); dc(pdf, "#e2e8f0"); pdf.roundedRect(x, y, 70, 70, 6, 6, "FD");
    pdf.setFont("helvetica", "bold"); pdf.setFontSize(9); tc(pdf, "#0f172a");
    pdf.text(c.name, x, y + 82);
    pdf.setFont("helvetica", "normal"); pdf.setFontSize(8); tc(pdf, "#94a3b8");
    pdf.text(c.hex, x, y + 93);
  });
  y += 108;

  // Secondary palette
  label(pdf, "Secondary Color Palette", M, y); y += 12;
  mock.design.secondaryPalette.forEach((c, i) => {
    const x = M + i * 90;
    card(pdf, x, y, 80, 36);
    fc(pdf, c.hex); pdf.roundedRect(x + 8, y + 10, 18, 18, 3, 3, "F");
    pdf.setFont("helvetica", "bold"); pdf.setFontSize(8); tc(pdf, "#0f172a");
    pdf.text(c.name, x + 30, y + 18);
    pdf.setFont("helvetica", "normal"); pdf.setFontSize(7); tc(pdf, "#94a3b8");
    pdf.text(c.hex, x + 30, y + 28);
  });
  y += 52;

  // Typography
  label(pdf, "Typography System", M, y); y += 12;
  card(pdf, M, y, CW, 56);
  pdf.setFont("helvetica", "normal"); pdf.setFontSize(8); tc(pdf, "#94a3b8");
  pdf.text(`Display — ${mock.design.typography.heading}`, M + 10, y + 14);
  pdf.setFont("helvetica", "bold"); pdf.setFontSize(20); tc(pdf, "#0f172a");
  pdf.text(mock.design.typography.headingExample, M + 10, y + 36, { maxWidth: CW - 20 });
  y += 64;

  card(pdf, M, y, CW, 44);
  pdf.setFont("helvetica", "normal"); pdf.setFontSize(8); tc(pdf, "#94a3b8");
  pdf.text(`Body — ${mock.design.typography.body}`, M + 10, y + 14);
  pdf.setFontSize(10); tc(pdf, "#475569");
  pdf.text(mock.design.typography.bodyExample, M + 10, y + 30, { maxWidth: CW - 20 });
  y += 54;

  // Logo direction
  label(pdf, "Logo Direction", M, y); y += 10;
  const logoLines = pdf.splitTextToSize(mock.design.logoDirection, CW - 90);
  card(pdf, M, y, CW, Math.max(logoLines.length * 14 + 24, 60));
  fc(pdf, "#1e293b"); pdf.roundedRect(M + 10, y + 10, 50, 40, 4, 4, "F");
  pdf.setFont("helvetica", "bold"); pdf.setFontSize(14); tc(pdf, "#ffffff");
  pdf.text("BF", M + 22, y + 35);
  bodyText(pdf, mock.design.logoDirection, M + 72, y + 18, CW - 90);
  y += Math.max(logoLines.length * 14 + 34, 70);

  // Visual language
  label(pdf, "Visual Language", M, y); y += 12;
  let vx = M;
  mock.design.visualLanguage.forEach((v) => {
    const vw = pdf.getStringUnitWidth(v) * 9 + 16;
    fc(pdf, "#ecfdf5"); dc(pdf, "#a7f3d0"); pdf.roundedRect(vx, y, vw, 16, 8, 8, "FD");
    pdf.setFont("helvetica", "bold"); pdf.setFontSize(8); tc(pdf, "#065f46");
    pdf.text(v, vx + 8, y + 11);
    vx += vw + 6;
  });

  footer(pdf);
}

// ── PAGE 5: COPY ──────────────────────────────────────────────────────────────
function copyPage(pdf: jsPDF, mock: MockData) {
  pageHeader(pdf, "Copy Agent · Brand Voice", "Brand Story, Messaging & Copy");
  let y = 68;

  // Tagline banner
  fc(pdf, "#0f172a"); pdf.roundedRect(M, y, CW, 58, 6, 6, "F");
  pdf.setFont("helvetica", "bold"); pdf.setFontSize(8); tc(pdf, "#3b82f6");
  pdf.text("THE TAGLINE", M + 12, y + 16);
  pdf.setFont("helvetica", "bolditalic"); pdf.setFontSize(20); tc(pdf, "#ffffff");
  pdf.text(`"${mock.copy.tagline}"`, M + 12, y + 40, { maxWidth: CW - 24 });
  y += 68;

  // Hero copy
  label(pdf, "Homepage Hero", M, y); y += 10;
  card(pdf, M, y, CW, 56);
  pdf.setFont("helvetica", "bold"); pdf.setFontSize(14); tc(pdf, "#0f172a");
  pdf.text(mock.copy.heroHeadline, M + 12, y + 20, { maxWidth: CW - 24 });
  pdf.setFont("helvetica", "normal"); pdf.setFontSize(10); tc(pdf, "#475569");
  const heroSubLines = pdf.splitTextToSize(mock.copy.heroSubheadline, CW - 24);
  pdf.text(heroSubLines, M + 12, y + 36);
  y += 66;

  // Elevator pitch
  label(pdf, "Elevator Pitch", M, y); y += 10;
  const epLines = pdf.splitTextToSize(mock.copy.elevatorPitch, CW - 20);
  card(pdf, M, y, CW, epLines.length * 14 + 24);
  pdf.setFont("helvetica", "bold"); pdf.setFontSize(10); tc(pdf, "#0f172a");
  pdf.text(epLines, M + 10, y + 18);
  y += epLines.length * 14 + 34;

  // Brand story
  label(pdf, "Brand Story", M, y); y += 10;
  const storyLines = pdf.splitTextToSize(mock.copy.brandStory, CW - 20);
  const storyH = storyLines.length * 13 + 24;
  card(pdf, M, y, CW, storyH);
  bodyText(pdf, mock.copy.brandStory, M + 10, y + 16, CW - 20);
  y += storyH + 10;

  // Marketing messages
  label(pdf, "Key Marketing Messages", M, y); y += 10;
  mock.copy.marketingMessages.forEach((msg) => {
    const msgLines = pdf.splitTextToSize(msg, CW - 30);
    const mh = msgLines.length * 13 + 20;
    card(pdf, M, y, CW, mh, "#fffbeb", "#fde68a");
    pdf.setFont("helvetica", "bold"); pdf.setFontSize(11); tc(pdf, "#d97706");
    pdf.text("★", M + 10, y + 15);
    pdf.setFont("helvetica", "bold"); pdf.setFontSize(9); tc(pdf, "#92400e");
    pdf.text(msgLines, M + 24, y + 15);
    y += mh + 6;
  });

  footer(pdf);
}

// ── PAGE 6: COHERENCE ─────────────────────────────────────────────────────────
function coherencePage(pdf: jsPDF, mock: MockData) {
  pageHeader(pdf, "Coherence Agent · AI Validation", "Brand Coherence Analysis");
  let y = 68;

  // Score + metrics row
  card(pdf, M, y, 110, 90, "#eff6ff", "#bfdbfe");
  pdf.setFont("helvetica", "bold"); pdf.setFontSize(42); tc(pdf, "#1d4ed8");
  pdf.text(`${mock.coherence.score}`, M + 12, y + 56);
  pdf.setFont("helvetica", "bold"); pdf.setFontSize(8); tc(pdf, "#60a5fa");
  pdf.text("GLOBAL SCORE", M + 10, y + 70);

  const metrics = [
    { label: "Tone Consistency", value: mock.coherence.toneConsistency },
    { label: "Audience Alignment", value: mock.coherence.audienceAlignment },
    { label: "Visual Consistency", value: mock.coherence.visualConsistency },
    { label: "Messaging Alignment", value: mock.coherence.messagingAlignment },
    { label: "Strategic Consistency", value: mock.coherence.strategicConsistency },
  ];
  const barX = M + 120;
  const barW = CW - 120;
  metrics.forEach((m, i) => {
    const my = y + 6 + i * 17;
    pdf.setFont("helvetica", "normal"); pdf.setFontSize(9); tc(pdf, "#475569");
    pdf.text(m.label, barX, my + 5);
    pdf.setFont("helvetica", "bold"); tc(pdf, "#0f172a");
    pdf.text(`${m.value}%`, barX + barW, my + 5, { align: "right" });
    fc(pdf, "#e2e8f0"); dc(pdf, "#e2e8f0"); pdf.roundedRect(barX, my + 8, barW, 5, 2, 2, "FD");
    fc(pdf, "#2563eb"); dc(pdf, "#2563eb");
    pdf.roundedRect(barX, my + 8, barW * m.value / 100, 5, 2, 2, "FD");
  });
  y += 100;

  // Validation summary
  label(pdf, "AI Validation Summary", M, y); y += 10;
  const sumLines = pdf.splitTextToSize(mock.coherence.validationSummary, CW - 20);
  card(pdf, M, y, CW, sumLines.length * 14 + 24, "#eff6ff", "#bfdbfe");
  pdf.setFont("helvetica", "bold"); pdf.setFontSize(10); tc(pdf, "#1e40af");
  pdf.text(sumLines, M + 10, y + 16);
  y += sumLines.length * 14 + 34;

  // Recommendations
  label(pdf, "Strategic Recommendations", M, y); y += 10;
  mock.coherence.recommendations.forEach((rec) => {
    const rlines = pdf.splitTextToSize(rec, CW - 30);
    const rh = rlines.length * 13 + 20;
    card(pdf, M, y, CW, rh);
    pdf.setFont("helvetica", "bold"); pdf.setFontSize(12); tc(pdf, "#d97706");
    pdf.text("→", M + 10, y + 16);
    bodyText(pdf, rec, M + 24, y + 16, CW - 34);
    y += rh + 6;
  });

  footer(pdf);
}

// ── MAIN EXPORT FUNCTION ──────────────────────────────────────────────────────
export async function generateBrandKitPDF(data: BrandData, mock: MockData): Promise<void> {
  const jsPDFLib = (await import("jspdf")).default;
  const pdf = new jsPDFLib({ orientation: "portrait", unit: "pt", format: "a4" });

  // Page 1
  coverPage(pdf, data, mock);
  pdf.addPage();

  // Page 2
  researchPage(pdf, mock);
  pdf.addPage();

  // Page 3
  strategyPage(pdf, mock);
  pdf.addPage();

  // Page 4
  designPage(pdf, mock);
  pdf.addPage();

  // Page 5
  copyPage(pdf, mock);
  pdf.addPage();

  // Page 6
  coherencePage(pdf, mock);

  pdf.save(`${data.startupName.replace(/\s+/g, "_")}_BrandKit.pdf`);
}
